/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_lipreading_android_FeatureExtractor */

#ifndef _Included_edu_lipreading_android_FeatureExtractor
#define _Included_edu_lipreading_android_FeatureExtractor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_lipreading_android_FeatureExtractor
 * Method:    nativeCreateObject
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_edu_lipreading_android_FeatureExtractor_nativeCreateObject
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     edu_lipreading_android_FeatureExtractor
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_lipreading_android_FeatureExtractor_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     edu_lipreading_android_FeatureExtractor
 * Method:    nativeDetect
 * Signature: (JJJ[I)V
 */
JNIEXPORT void JNICALL Java_edu_lipreading_android_FeatureExtractor_nativeDetect
  (JNIEnv *, jclass, jlong, jlong, jlong, jintArray);

#ifdef __cplusplus
}
#endif
#endif
